/**
 * Payment Controller
 * Creates and verifies Razorpay Orders for the membership registration fee.
 * Razorpay is used purely as the payment rail here - the actual invoice
 * (PDF, storage, emailing) is generated by our own invoiceService once the
 * payment is confirmed during registration (see authController.register).
 */

const { getRazorpayInstance } = require("../utils/razorpayClient");
const { verifyPaymentSignature } = require("../utils/razorpaySignature");
const { getFeeBreakdown } = require("../config/fees");

/**
 * Create a Razorpay order for the registration fee. The amount is computed
 * entirely server-side (getFeeBreakdown) so it cannot be tampered with by
 * the client.
 * POST /api/payment/create-order
 * Body: name, email, mobile, companyName - used only as order notes
 */
const createOrder = async (req, res) => {
  try {
    const { name, email, mobile, companyName } = req.body;

    if (!name || !email || !mobile) {
      return res.status(400).json({
        success: false,
        message: "name, email and mobile are required to start payment",
      });
    }

    const feeBreakdown = getFeeBreakdown();

    const notes = {
      "Member Name": name,
      Email: email,
      Mobile: mobile,
    };
    if (companyName) {
      notes.Company = companyName;
    }

    const order = await getRazorpayInstance().orders.create({
      amount: feeBreakdown.totalPaise,
      currency: feeBreakdown.currency,
      receipt: `reg_${Date.now()}`,
      notes,
    });

    return res.status(200).json({
      success: true,
      message: "Order created successfully",
      data: {
        orderId: order.id,
        amount: order.amount,
        currency: order.currency,
        keyId: process.env.RAZORPAY_KEY_ID,
      },
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message:
        error?.error?.description ||
        error.message ||
        "Unable to create payment order",
    });
  }
};

/**
 * Confirm a captured payment's signature. This is only a checkpoint used by
 * the client after Razorpay Checkout closes - the payment is authoritatively
 * (re)verified again in authController.register before a user is created.
 * POST /api/payment/verify
 * Body: razorpayOrderId, razorpayPaymentId, razorpaySignature
 */
const verifyPayment = async (req, res) => {
  try {
    const { razorpayOrderId, razorpayPaymentId, razorpaySignature } = req.body;

    if (!verifyPaymentSignature(razorpayOrderId, razorpayPaymentId, razorpaySignature)) {
      return res.status(400).json({
        success: false,
        message: "Payment verification failed.",
      });
    }

    return res.status(200).json({
      success: true,
      message: "Payment verified",
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error?.error?.description || error.message || "Unable to verify payment",
    });
  }
};

module.exports = {
  createOrder,
  verifyPayment,
};
